In [27]:
import numpy as np
import csv

In [29]:
a=[12,2,1,5]
a.insert(1,2)
print(a)

[12, 2, 2, 1, 5]


In [30]:
p=[[10,20,0],[5,9,84],[45,5,68]]
ar=np.array(p)
print(ar.T)
k=np.insert(ar,1,np.array([1,2,3]),axis=0)
delt=np.delete(ar,1,axis=1)
print(k)
print(delt)

[[10  5 45]
 [20  9  5]
 [ 0 84 68]]
[[10 20  0]
 [ 1  2  3]
 [ 5  9 84]
 [45  5 68]]
[[10  0]
 [ 5 84]
 [45 68]]


In [45]:
data=[
    ['Name', 'Roll', 'Math','Chem','Phy','Eng'],
    ['a',355,85,65,55,63],
    ['b',356,78,71,85,45],
    ['c',3,98,55,56,65],
    ['d',4,84,96,74,52],
    ['e',5,89,96,74,63],
    ['f',6,63,23,45,15]
]
with open("student.csv","r+")as obj:
    list=csv.writer(obj)
    list.writerows(data)

In [46]:
with open("student.csv", mode="r") as file:
    reader= csv.DictReader(file)
    da=[row for row in reader]
for student in da:
    print(student)

{'Name': 'a', 'Roll': '355', 'Math': '85', 'Chem': '65', 'Phy': '55', 'Eng': '63'}
{'Name': 'b', 'Roll': '356', 'Math': '78', 'Chem': '71', 'Phy': '85', 'Eng': '45'}
{'Name': 'c', 'Roll': '3', 'Math': '98', 'Chem': '55', 'Phy': '56', 'Eng': '65'}
{'Name': 'd', 'Roll': '4', 'Math': '84', 'Chem': '96', 'Phy': '74', 'Eng': '52'}
{'Name': 'e', 'Roll': '5', 'Math': '89', 'Chem': '96', 'Phy': '74', 'Eng': '63'}
{'Name': 'f', 'Roll': '6', 'Math': '63', 'Chem': '23', 'Phy': '45', 'Eng': '15'}


In [47]:
m=[]
c=[]
p=[]
e=[]
for student in da:
        m.append(int(student['Math'])),
        c.append(int(student['Chem'])),
        p.append(int(student['Phy'])),
        e.append(int(student['Eng']))
print(f"Math -> high {max(m)} , low {min(m)}")
print(f"CHEM -> high {max(c)} , low {min(c)}")
print(f"PHY -> high {max(p)} , low {min(p)}")
print(f"ENG -> high {max(e)} , low {min(e)}")

Math -> high 98 , low 63
CHEM -> high 96 , low 23
PHY -> high 85 , low 45
ENG -> high 65 , low 15
