In [1]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
X = np.array([
    [0,0,0],
    [0,0,1],
    [0,1,0],
    [0,1,1],
    [1,0,0],
    [1,0,1],
    [1,1,0],
    [1,1,1]
])

Y = np.array([
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1
])

In [3]:
model = Sequential()
model.add(Dense(4,
                input_dim=3,
                activation='relu'))
model.add(Dense(1,
                activation='sigmoid'))

C:\Users\umair\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [4]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [10]:
model.fit(
    X,
    Y,
    epochs=1500,
    verbose=0
)

In [11]:
predictions = model.predict(X)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step


In [12]:
predictions = model.predict(X)

print("Predicted Output:")

for i in range(len(X)):
    output = 1 if predictions[i][0] >= 0.5 else 0
    print(f"{X[i]} --> {output}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step
Predicted Output:
[0 0 0] --> 0
[0 0 1] --> 0
[0 1 0] --> 0
[0 1 1] --> 0
[1 0 0] --> 0
[1 0 1] --> 0
[1 1 0] --> 0
[1 1 1] --> 1
